<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>04_Exploratory_Data_Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="04_exploratory_data_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="04_exploratory_data_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="04_exploratory_data_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="04_exploratory_data_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04_exploratory_data_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="04_exploratory_data_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04_exploratory_data_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04_exploratory_data_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04_exploratory_data_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04_exploratory_data_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">04_Exploratory_Data_Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load Packages</h2>
<p>These are the packages that have been used throughout the following document: <code>here</code>, <code>tidyverse</code>, <code>lubridate</code>, <code>knitr</code></p>
<p><em>other packages will be loaded as needed</em></p>
</section>
<section id="reading-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-data">Reading data</h2>
</section>
<section id="creating-data-frames-for-bivariate-and-multivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="creating-data-frames-for-bivariate-and-multivariate-analysis">Creating data frames for bivariate and multivariate analysis</h2>
</section>
<section id="influenza-data" class="level2">
<h2 class="anchored" data-anchor-id="influenza-data">Influenza data</h2>
<section id="distribution-of-coverage-by-number-of-doses-and-the-degree-of-coverage-since-october-2022" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-coverage-by-number-of-doses-and-the-degree-of-coverage-since-october-2022">Distribution of coverage by number of doses and the degree of coverage (since october 2022)</h3>
<p><strong>By degree of coverage</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>By number of doses</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  influenza_coverage_dosage individuals proportion
1                         0        3684 0.67497252
2                         1         408 0.07475266
3                         2        1366 0.25027483</code></pre>
</div>
</div>
<p>A majority of the children (68%) who are eligible for the influenza vax have not receieved the vaccine at all (i.e.&nbsp;0 doses or Not vaxxed). However, within the children who have receieved at least one dose of the vaccine (~32%), a much greater proportion of them are considered fully vaxxed than being partially vaxxed (a ratio of 10:1).</p>
<p>This is supported by data on the number of doses received, the ratio of individuals who have received 2 doses as compared to 1 dose is roughly 3:1 (25:7.5). The discrepnacy in ratios can be explained by children below the age of 5 being considered fully vaxxed individuals upon receiving 1 or more doses of the influenza vax</p>
</section>
</section>
<section id="covid-data" class="level2">
<h2 class="anchored" data-anchor-id="covid-data">Covid data</h2>
<section id="distribution-of-coverage-by-number-of-doses-and-the-degree-of-coverage-since-october-2022-1" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-coverage-by-number-of-doses-and-the-degree-of-coverage-since-october-2022-1">Distribution of coverage by number of doses and the degree of coverage (since october 2022)</h3>
<p><strong>By degree of coverage</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  covid_coverage_age individuals proportion
1         Not vaxxed        4338  0.8273889
2   Partially vaxxed         305  0.0581728
3       Fully vaxxed         600  0.1144383</code></pre>
</div>
</div>
<p><strong>By number of doses</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  covid_coverage_dosage individuals proportion
1                     0        4338 0.79479663
2                     1         113 0.02070355
3                     2         265 0.04855258
4                     3         742 0.13594723</code></pre>
</div>
</div>
<p>Majority of individuals who exist in</p>
<p>The data on covid vaccinations tells a similar story to that of influenza vaccinations. Namely, the proportion of eligible children who are not vaxxed at all remains high at 80% of the children body. However, the proportion of individuals who are partially vaccinated – less than 3 doses for individuals over the age of 5 – is significantly higher (partial:full = 1:3) than that for those who received the influenza vaccine (partial:full = 1:10).</p>
<p>Referencing the number of doses of the covid vaccine received by individuals, we note that 13.6% of the eligible children received 3 doses of the covid vaccine, 1.3% lower than the 14.9% of children who are fully vaxxed – this is explained by children under 5y/o being classified as fully vaccinated as long as they have 1 or more doses of the covid vaccine due to variances in the vaccination schedule of covid vacccines for that age group. Note that majority (85%) of the 5.6% children who are partially vaccinated received 2 doses, 4.8% of all eligible children.</p>
<p><strong><em>Why are there more children who are partially vaccinated for covid as opposed to the influenza vaccination?</em></strong></p>
</section>
</section>
<section id="multivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-analysis">Multivariate analysis</h2>
<section id="independent-variables" class="level3">
<h3 class="anchored" data-anchor-id="independent-variables">Independent variables</h3>
<p>Package used: <code>GGally</code> for pairs plots?</p>
</section>
</section>
<section id="bivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-analysis">Bivariate analysis</h2>
<section id="independent-variables-1" class="level3">
<h3 class="anchored" data-anchor-id="independent-variables-1">Independent variables</h3>
<p>Questions to be asked</p>
</section>
</section>
<section id="number-of-individuals" class="level2">
<h2 class="anchored" data-anchor-id="number-of-individuals">Number of individuals</h2>
<section id="total-number-of-individuals" class="level3">
<h3 class="anchored" data-anchor-id="total-number-of-individuals">Total number of individuals</h3>
<p>The following is a breakdown of the number of households according to number of individuals per household</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">individuals</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">households</td>
<td style="text-align: right;">7995</td>
<td style="text-align: right;">10901</td>
<td style="text-align: right;">7149</td>
<td style="text-align: right;">5003</td>
<td style="text-align: right;">1429</td>
<td style="text-align: right;">381</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">households_w_COI</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">2244</td>
<td style="text-align: right;">2378</td>
<td style="text-align: right;">673</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">percentage_w_COI</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Where the bars represent the number of household for each household size and the line graph represents the number of households <strong>with a child of interest</strong> for each household size</p>
<p>Responses from households of 3 to 5 people posses the majority of children of interest. Households comprise of 2 individuals had very little responses with a child of interest which could be attributed to there being less single-child parents.</p>
<p>To examine how the number of individuals in a household affects the children of interest then, we should primarily be looking at households of at least 2 individuals (children of interest = 109), and up to 7 people (children of interest = 39).</p>
<p><strong><em>Does the number of individuals in a household affect</em></strong></p>
<p>Breakdown of the number of households by household size – for those with covid vaccination data</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   household_total count
             &lt;int&gt; &lt;int&gt;
 1               2   107
 2               3  1957
 3               4  2285
 4               5   666
 5               6   172
 6               7    38
 7               8    11
 8               9     3
 9              10     1
10              11     1
11              25     2</code></pre>
</div>
</div>
<p><strong><em>1. The child’s covid vaccination status</em></strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For household sizes of 2 to 7 individuals, we see a positive linear relationship between household size and being fully vaccinated. The apparent continuation of this trend with households of size 9 is deceptive as it is due to the small sample size of households of 9 individuals (n = 3)</p>
<p><strong><em>2. The number of doses of the covid vaccine the child receives</em></strong></p>
<p>*Following data on the degree of covid coverage by total household size, we limit the range of household sizes to household sizes of sufficiently large (n &gt;= 30) counts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using simple linear regression to test the effect of an increasing number of household members on the proportions of individuals receiving 0 to 3 doses of the covid vaccine respectively.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There is a positive linear relationship between total household size and the number of individuals receiving 1 &amp; 3 doses of the covid vaccine.</p>
<p>This is accounted for by the negative linear relationship between total household size and the number of individuals receiving 0 doses of the covid vaccine – indicating that more invidiuals who were previously unvaccinated were getting vaccinated.</p>
<p>However, there was no significant relationship between total household size and the proportion of individuals who received 2 doses of the covid vaccine.</p>
<p><strong><em>3.the child’s (influenza) vaccination status</em></strong> Breakdown of the number of households by household size – for those with influenza vaccination data</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   household_total count
             &lt;int&gt; &lt;int&gt;
 1               2    90
 2               3  1533
 3               4  1716
 4               5   524
 5               6   145
 6               7    30
 7               8     7
 8               9     3
 9              10     1
10              11     1
11              25     2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We limit the range of observations to households of sizes from 2 to 7 people such that the sample for each household size is sufficiently large (n &gt;= 30).</p>
<p>Whilst it may appear that the proportion of individuals who get fully vaccinated increases with an increasing household size, this does not hold true once we limit the range of observations to households of sizes from 2 to 7 people such that the sample for each household size is sufficiently large (n &gt;= 30).</p>
<p>The proportion of children of interest becoming fully vaccinated with the influenza vaccine fluctuates with the total number of individuals in a household. This deviates from the trend, where the proportion of individuals becoming fully vaccinated increased as the total number of individuals in a household increased, shown with the covid vaccine.</p>
<pre><code>-   the number of doses of the influenza vaccine the child receives</code></pre>
<p>*Following data on the degree of influenza coverage by total household size, we limit the range of household sizes to household sizes of sufficiently large (n &gt;= 30) counts.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using simple linear regression to test the effect of an increasing number of household members on the proportions of individuals receiving 0 to 3 doses of the covid vaccine respectively.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The total number of individuals in a household is not indicative of the proportion of individuals who receive 0 doses of the influenza vaccine.</p>
<p>The proportion of individuals receiving 1 vaccine decreased with an increasing number of individuals in a household whilst The proportion of individuals receiving 2 doses of the influenza vacine increased with an increasing number of individuals in the household.</p>
</section>
<section id="number-of-aunts-and-uncles" class="level3">
<h3 class="anchored" data-anchor-id="number-of-aunts-and-uncles">Number of aunts and uncles</h3>
<p><strong><em>Does the number of aunts and uncles a child has affect:</em></strong> The following is a breakdown of the number of households with respect to the number of aunts and uncles that the child of interest has – for those with a valid covid vaccination status</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  child_auntcles count
1              0  5209
2              1    25
3              2     7
4              3     2</code></pre>
</div>
</div>
<p><strong><em>1. The child’s (covid) vaccination status</em></strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Due to the small sample of households where there are both children of interest with valid covid vaccination data and aunts or uncles living with them, let us recatogrise such data to determine if having an aunt or uncle living with a child impacts their chances of receiving the covid vaccine at all</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   auntcles [2]
  auntcles covid_coverage count
  &lt;chr&gt;    &lt;chr&gt;          &lt;int&gt;
1 No       No              4309
2 No       Yes              900
3 Yes      No                29
4 Yes      Yes                5</code></pre>
</div>
</div>
<p>re-categorising the data, we get the following contingency table</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  chisq_auntcles_cov
X-squared = 0.02819, df = 1, p-value = 0.8667</code></pre>
</div>
</div>
<p>Since the p-value (0.8667) is not less than 0.05, we fail to reject the null hypothesis. Thus Covid vaccination uptake of a child is independent of the presence of aunts and uncles in the household.</p>
<p><strong><em>2. The number of doses of the covid vaccine the child receives</em></strong> Refer to data on the degree of coverage for the covid vaccine with respect to the presence of aunts and uncles</p>
<p><strong><em>3. The child’s (influenza) vaccination status</em></strong> The following is a breakdown of the number of households with respect to the number of aunts and uncles the child of interest has – for those with a valid influenza vaccination status</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  child_auntcles count
1              0  4027
2              1    18
3              2     5
4              3     2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For all cases where children had aunts/uncles living with them, the children of interest were not vaccinated with the influenza vaccine.</p>
<p>To carry out a chi-squared test:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
# Groups:   auntcles [2]
  auntcles influenza_coverage count
  &lt;chr&gt;    &lt;chr&gt;              &lt;int&gt;
1 No       No                  3659
2 No       Yes                  368
3 Yes      No                    25</code></pre>
</div>
</div>
<p>re-categorising the data, we get the following contingency table</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  chisq_auntcles_cov
X-squared = 0.02819, df = 1, p-value = 0.8667</code></pre>
</div>
</div>
<p>As the p-value (p = 0.2164) is not smaller than 0.05, we cannot reject the null. Thus, the uptake of the influenza vaccine by a child is independent of the presence of aunts or ucles living in the same household.</p>
<p><strong><em>4. The number of doses of the influenza vaccine the child receives</em></strong> Refer to data on the degree of coverage for the influenza vaccine with respect to the presence of aunts and uncles.</p>
</section>
<section id="number-of-vulnerable-individuals" class="level3">
<h3 class="anchored" data-anchor-id="number-of-vulnerable-individuals">Number of vulnerable individuals</h3>
<p><strong><em>Does the number of vulnerable individuals living in the same household (this includes individuals who are bedriden, need ventilation and need feeding) affect:</em></strong></p>
<p><strong><em>The uptake of the covid vaccine?</em></strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  vulnerable_individuals count
                   &lt;int&gt; &lt;int&gt;
1                      0  5421
2                      1    25
3                      2     3
4                      3     9</code></pre>
</div>
</div>
<p>plotting the uptake of the covid vaccine by dosage against the number of vulnerable individuals in a household:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_exploratory_data_analysis_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Given the small number of households who have 1 or more vulnerable individuals living with them, let’s reframe this variable to investigate the effect of <strong>the presence</strong> of vulnerable individuals on the number of doses of the covid vaccine the individuals receives.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  vulnerable_individuals covid_coverage count
1                      0             No  4313
2                      0            yes  1108
3                      1             No    17
4                      3            yes     3
5                      3             No     6
6                      1            yes     8
7                      2            yes     1
8                      2             No     2</code></pre>
</div>
</div>
</section>
<section id="number-of-grandparents" class="level3">
<h3 class="anchored" data-anchor-id="number-of-grandparents">Number of grandparents</h3>
<p><strong><em>Does the number of grandparents living in the same household affect:</em></strong> <strong><em>1. The number of doses of the covid vaccine the child receives</em></strong> The following is a breakdown of the households by the number of grandparents per household</p>
</section>
</section>
<section id="child-and-siblings" class="level2">
<h2 class="anchored" data-anchor-id="child-and-siblings">Child and siblings</h2>
<section id="total-number-of-siblings" class="level3">
<h3 class="anchored" data-anchor-id="total-number-of-siblings">Total number of siblings</h3>
<ul>
<li>Does the number of siblings living with the child in the same household affect:</li>
</ul>
</section>
<section id="number-of-brothers-andor-siblings" class="level3">
<h3 class="anchored" data-anchor-id="number-of-brothers-andor-siblings">Number of brothers and/or siblings</h3>
<ul>
<li>Does the number of sisters and or brothers living in the same household as the child affect:</li>
</ul>
</section>
<section id="number-of-siblings-at-the-time-of-vaccination" class="level3">
<h3 class="anchored" data-anchor-id="number-of-siblings-at-the-time-of-vaccination">Number of siblings at the time of vaccination</h3>
</section>
</section>
<section id="parents" class="level2">
<h2 class="anchored" data-anchor-id="parents">Parents</h2>
<section id="number-of-parents" class="level3">
<h3 class="anchored" data-anchor-id="number-of-parents">Number of parents</h3>
<ul>
<li><p>Does the number of parents a child has affect:</p>
<ul>
<li><p>the child’s (covid) vaccination status</p></li>
<li><p>the number of doses of the covid vaccine the child receives</p></li>
<li><p>the child’s (influenza) vaccination status</p></li>
<li><p>the number of doses of the influenza vaccine the child receive</p></li>
</ul></li>
</ul>
</section>
<section id="parents-marital-status" class="level3">
<h3 class="anchored" data-anchor-id="parents-marital-status">Parent’s marital status</h3>
<ul>
<li>Does the marital status of the parents affect:</li>
</ul>
</section>
</section>
<section id="finances" class="level2">
<h2 class="anchored" data-anchor-id="finances">Finances</h2>
<section id="annual-household-income" class="level3">
<h3 class="anchored" data-anchor-id="annual-household-income">Annual household income</h3>
<ul>
<li>Does the family’s annual household income affect:</li>
</ul>
</section>
</section>
<section id="chronic-illness" class="level2">
<h2 class="anchored" data-anchor-id="chronic-illness">Chronic illness</h2>
<section id="respondents-chronic-illness" class="level3">
<h3 class="anchored" data-anchor-id="respondents-chronic-illness">Respondent’s chronic illness</h3>
<ul>
<li>Does the presence of chronic illness in the responding parent affect:</li>
</ul>
</section>
</section>
<section id="industry-of-work" class="level2">
<h2 class="anchored" data-anchor-id="industry-of-work">Industry of work</h2>
<section id="respondent-parent-working-in-healthcare" class="level3">
<h3 class="anchored" data-anchor-id="respondent-parent-working-in-healthcare">Respondent parent working in healthcare</h3>
<ul>
<li>Does the respondent parent working in the healthcare sector affect:</li>
</ul>
</section>
</section>
<section id="parents-highest-educational-attianment" class="level2">
<h2 class="anchored" data-anchor-id="parents-highest-educational-attianment">Parent’s highest educational attianment</h2>
<section id="parents-highest-education-by-qualification" class="level3">
<h3 class="anchored" data-anchor-id="parents-highest-education-by-qualification">Parent’s highest education by qualification</h3>
<ul>
<li>Does the highest educational qualification of a child’s parents affect:</li>
</ul>
</section>
</section>
<section id="childs-parents-vaccination" class="level2">
<h2 class="anchored" data-anchor-id="childs-parents-vaccination">Child’s parent’s vaccination</h2>
<section id="parents-influenza-vaccination" class="level3">
<h3 class="anchored" data-anchor-id="parents-influenza-vaccination">Parent’s influenza vaccination</h3>
<ul>
<li>Does the influenza vaccination status of a child’s parents in the past year affect:</li>
</ul>
</section>
<section id="parents-covid-vaccination-dosage" class="level3">
<h3 class="anchored" data-anchor-id="parents-covid-vaccination-dosage">Parent’s covid vaccination (dosage)</h3>
<ul>
<li>Does the covid vaccination status of a child’s parents affect:</li>
</ul>
</section>
<section id="recency-of-parents-covid-vaccination" class="level3">
<h3 class="anchored" data-anchor-id="recency-of-parents-covid-vaccination">Recency of parent’s covid vaccination</h3>
<ul>
<li>Does the recency of a child’s parent’s covid vaccination affect:</li>
</ul>
</section>
<section id="childs-parents-yearly-vaccination-intention" class="level3">
<h3 class="anchored" data-anchor-id="childs-parents-yearly-vaccination-intention">Child’s parent’s yearly vaccination intention</h3>
<ul>
<li>Does the child’s parent’s intention to get the covid vaccine every year affect:</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>