---
title: "04_exploratory_DAG"
format: html
---
This document serves to store the dagitty code for the DAG to illustrate the codependencies between our variables we are exploring

updated dag
```{r}
dag {
"vaccine uptake" [outcome,pos="0.315,-0.557"]
age_cat [adjusted,pos="0.602,1.288"]
age_of_interest [adjusted,pos="0.872,0.656"]
birth_order [pos="-0.429,-0.157"]
child_grand [exposure,pos="-1.456,-0.957"]
child_parents [exposure,pos="-1.629,-2.506"]
child_siblings [exposure,pos="-0.903,0.612"]
father_employment_status [exposure,pos="0.329,1.793"]
father_highest_education [exposure,pos="-0.105,2.304"]
household_total [exposure,pos="-1.631,-0.295"]
mother_employment_status [exposure,pos="-0.803,2.212"]
mother_highest_education [exposure,pos="-1.331,1.935"]
parent_1_age [pos="-0.961,-2.243"]
parent_chronic_illness [exposure,pos="-0.512,-1.852"]
parent_covid_coverage [pos="0.530,-2.757"]
parent_covid_doses [pos="0.840,-1.781"]
parent_influenza [pos="1.071,-2.141"]
parents_healthcare [adjusted,pos="0.831,-0.097"]
parents_highest_education [exposure,pos="-1.508,0.976"]
parents_time_since_covvax [pos="0.452,-1.397"]
perception_xxx [adjusted,pos="0.060,-2.266"]
siblings_over_18 [adjusted,pos="-1.002,0.020"]
test_household_income [exposure,pos="-0.334,0.613"]
test_parents_marital_status [exposure,pos="-1.112,-1.703"]
age_cat -> "vaccine uptake"
age_of_interest -> "vaccine uptake"
age_of_interest -> age_cat
birth_order -> "vaccine uptake"
child_grand -> "vaccine uptake"
child_grand -> household_total [pos="-1.619,-0.914"]
child_parents -> "vaccine uptake"
child_parents -> child_grand
child_parents -> mother_employment_status
child_parents -> test_household_income
child_siblings -> "vaccine uptake"
child_siblings -> birth_order
child_siblings -> household_total
father_employment_status -> "vaccine uptake"
father_employment_status -> child_grand
father_employment_status -> test_household_income
father_highest_education -> "vaccine uptake"
father_highest_education -> child_siblings
father_highest_education -> father_employment_status
father_highest_education -> parents_highest_education
father_highest_education -> test_household_income
household_total -> "vaccine uptake"
mother_employment_status -> "vaccine uptake"
mother_employment_status -> child_grand
mother_employment_status -> test_household_income
mother_highest_education -> "vaccine uptake"
mother_highest_education -> child_siblings
mother_highest_education -> mother_employment_status
mother_highest_education -> parents_highest_education
mother_highest_education -> test_household_income
parent_1_age -> parent_chronic_illness
parent_1_age -> test_parents_marital_status
parent_chronic_illness -> "vaccine uptake"
parent_chronic_illness -> parent_covid_coverage [pos="-0.232,-2.932"]
parent_chronic_illness -> parent_covid_doses
parent_chronic_illness -> parent_influenza
parent_covid_coverage -> parent_covid_doses
parent_covid_doses -> parents_time_since_covvax
parents_healthcare -> "vaccine uptake"
parents_healthcare -> parent_covid_coverage
parents_healthcare -> parent_covid_doses
parents_healthcare -> parent_influenza
parents_healthcare -> parents_time_since_covvax
parents_highest_education -> "vaccine uptake"
parents_highest_education -> child_siblings
parents_highest_education -> household_total
parents_highest_education -> test_household_income
perception_xxx -> "vaccine uptake"
perception_xxx -> parent_covid_coverage
perception_xxx -> parent_influenza
perception_xxx -> parents_time_since_covvax
siblings_over_18 -> birth_order
siblings_over_18 -> child_grand
siblings_over_18 -> household_total
siblings_over_18 -> test_household_income
test_household_income -> "vaccine uptake"
test_household_income -> child_grand
test_household_income -> child_siblings
test_parents_marital_status -> "vaccine uptake"
test_parents_marital_status -> child_parents
test_parents_marital_status -> household_total
test_parents_marital_status -> test_household_income
}

```

old dag
```{r}
dag {
"vaccine uptake" [outcome,pos="0.315,-0.557"]
age_cat [adjusted,pos="0.540,1.723"]
age_of_interest [adjusted,pos="1.114,0.644"]
birth_order [adjusted,pos="-0.017,1.998"]
child_grand [exposure,pos="-1.882,-0.695"]
child_parents [exposure,pos="-1.406,-1.009"]
child_siblings [exposure,pos="-0.695,1.177"]
father_employment_status [pos="0.940,1.786"]
father_highest_education [pos="0.799,0.916"]
household_total [exposure,pos="-1.875,0.346"]
mother_employment_status [pos="-0.100,1.596"]
mother_highest_education [pos="-1.684,1.939"]
mother_stay_home [exposure,pos="0.100,0.308"]
parent_1_age [pos="-1.466,-2.088"]
parent_chronic_illness [exposure,pos="-0.766,-1.480"]
parent_covid_coverage [pos="0.436,-2.220"]
parent_covid_doses [pos="1.183,-1.172"]
parent_influenza [pos="1.031,-1.747"]
parents_healthcare [pos="1.150,-0.016"]
parents_highest_education [pos="-1.716,0.997"]
parents_time_since_covvax [pos="-0.443,-2.290"]
siblings_over_18 [pos="-0.908,2.243"]
test_household_income [exposure,pos="-1.230,0.110"]
test_parents_marital_status [exposure,pos="-0.738,-0.618"]
age_cat -> "vaccine uptake"
age_of_interest -> "vaccine uptake"
age_of_interest -> age_cat
age_of_interest -> mother_stay_home
birth_order -> "vaccine uptake"
child_grand -> "vaccine uptake"
child_grand -> household_total [pos="-2.302,-0.315"]
child_parents -> "vaccine uptake"
child_parents -> child_grand
child_parents -> mother_employment_status
child_parents -> mother_stay_home
child_parents -> test_household_income
child_siblings -> "vaccine uptake"
child_siblings -> birth_order
child_siblings -> household_total
father_employment_status -> child_grand
father_employment_status -> test_household_income
father_highest_education -> child_siblings
father_highest_education -> father_employment_status
father_highest_education -> parents_highest_education
father_highest_education -> test_household_income
mother_employment_status -> child_grand
mother_employment_status -> mother_stay_home
mother_employment_status -> test_household_income
mother_highest_education -> child_siblings
mother_highest_education -> mother_employment_status
mother_highest_education -> mother_stay_home [pos="-1.228,1.247"]
mother_highest_education -> parents_highest_education
mother_highest_education -> test_household_income
mother_stay_home -> "vaccine uptake"
mother_stay_home -> child_grand
mother_stay_home -> test_household_income
parent_1_age -> parent_chronic_illness
parent_1_age -> test_parents_marital_status
parent_chronic_illness -> "vaccine uptake"
parent_chronic_illness -> parent_covid_coverage
parent_chronic_illness -> parent_covid_doses
parent_chronic_illness -> parent_influenza
parent_covid_coverage -> "vaccine uptake"
parent_covid_doses -> "vaccine uptake"
parent_covid_doses -> parents_time_since_covvax
parent_influenza -> "vaccine uptake"
parents_healthcare -> "vaccine uptake"
parents_healthcare -> parent_covid_coverage
parents_healthcare -> parent_covid_doses
parents_healthcare -> parent_influenza
parents_healthcare -> parents_time_since_covvax
parents_highest_education -> child_siblings
parents_highest_education -> household_total
parents_highest_education -> mother_stay_home
parents_highest_education -> test_household_income
parents_time_since_covvax -> "vaccine uptake"
siblings_over_18 -> birth_order
siblings_over_18 -> child_grand
siblings_over_18 -> household_total
siblings_over_18 -> parents_highest_education
siblings_over_18 -> test_household_income
test_household_income -> "vaccine uptake"
test_household_income -> child_grand
test_household_income -> child_siblings
test_parents_marital_status -> "vaccine uptake"
test_parents_marital_status -> child_parents
test_parents_marital_status -> household_total
test_parents_marital_status -> mother_stay_home
test_parents_marital_status -> test_household_income
}
```

converting to a dagitty object
```{r}
dag_code <- 
'
dag {
"vaccine uptake" [outcome,pos="0.315,-0.557"]
age_cat [adjusted,pos="0.540,1.723"]
age_of_interest [adjusted,pos="1.151,0.502"]
birth_order [adjusted,pos="-0.509,2.039"]
child_grand [exposure,pos="-1.899,-0.349"]
child_parents [exposure,pos="-1.323,-0.883"]
child_siblings [exposure,pos="-1.305,0.710"]
father_employment_status [pos="0.940,1.786"]
father_highest_education [pos="0.799,0.916"]
household_total [pos="-1.922,0.592"]
mother_employment_status [pos="-0.100,1.596"]
mother_highest_education [pos="-1.684,1.939"]
mother_stay_home [pos="0.169,0.654"]
parent_1_age [pos="-1.604,-2.032"]
parent_chronic_illness [exposure,pos="-0.523,-1.320"]
parent_covid_coverage [pos="0.436,-2.220"]
parent_covid_doses [pos="1.183,-1.172"]
parent_influenza [pos="1.031,-1.747"]
parents_healthcare [pos="1.150,-0.016"]
parents_highest_education [pos="-1.885,1.307"]
parents_time_since_covvax [pos="-0.367,-1.975"]
siblings_over_18 [pos="-1.070,2.049"]
test_household_income [exposure,pos="-0.757,0.655"]
test_parents_marital_status [exposure,pos="-0.739,-0.059"]
vulnerable_individuals [exposure,pos="-1.676,-1.416"]
age_cat -> "vaccine uptake"
age_of_interest -> "vaccine uptake"
age_of_interest -> age_cat
age_of_interest -> mother_stay_home
birth_order -> "vaccine uptake"
birth_order -> age_of_interest
birth_order -> child_grand
child_grand -> "vaccine uptake"
child_grand -> household_total [pos="-2.302,-0.315"]
child_grand -> vulnerable_individuals
child_parents -> "vaccine uptake"
child_parents -> child_grand
child_parents -> mother_employment_status
child_parents -> mother_stay_home
child_parents -> test_household_income
child_siblings -> "vaccine uptake"
child_siblings -> age_of_interest
child_siblings -> birth_order
child_siblings -> household_total
father_employment_status -> child_grand
father_employment_status -> test_household_income
father_highest_education -> child_siblings
father_highest_education -> father_employment_status
father_highest_education -> parents_highest_education
father_highest_education -> test_household_income
household_total -> test_household_income
mother_employment_status -> child_grand
mother_employment_status -> mother_stay_home
mother_employment_status -> test_household_income
mother_highest_education -> child_siblings
mother_highest_education -> mother_employment_status
mother_highest_education -> mother_stay_home [pos="-1.228,1.247"]
mother_highest_education -> parents_highest_education
mother_highest_education -> test_household_income
mother_stay_home -> child_grand
mother_stay_home -> test_household_income
parent_1_age -> parent_chronic_illness
parent_1_age -> vulnerable_individuals
parent_chronic_illness -> "vaccine uptake"
parent_chronic_illness -> parent_covid_coverage
parent_chronic_illness -> parent_covid_doses
parent_chronic_illness -> parent_influenza
parent_chronic_illness -> vulnerable_individuals
parent_chronic_illness <-> test_parents_marital_status
parent_covid_coverage -> "vaccine uptake"
parent_covid_doses -> "vaccine uptake"
parent_covid_doses -> parents_time_since_covvax
parent_influenza -> "vaccine uptake"
parents_healthcare -> "vaccine uptake"
parents_healthcare -> parent_covid_coverage
parents_healthcare -> parent_covid_doses
parents_healthcare -> parent_influenza
parents_healthcare -> parents_time_since_covvax
parents_highest_education -> child_siblings
parents_highest_education -> household_total
parents_highest_education -> mother_stay_home
parents_highest_education -> test_household_income
parents_time_since_covvax -> "vaccine uptake"
siblings_over_18 -> birth_order
siblings_over_18 -> child_grand
siblings_over_18 -> household_total
siblings_over_18 -> parents_highest_education
siblings_over_18 -> test_household_income
test_household_income -> "vaccine uptake"
test_household_income -> child_grand
test_household_income -> child_siblings
test_parents_marital_status -> "vaccine uptake"
test_parents_marital_status -> child_parents
test_parents_marital_status -> household_total
test_parents_marital_status -> mother_stay_home
test_parents_marital_status -> test_household_income
vulnerable_individuals -> "vaccine uptake"
}
'
```
turn it into a dagitty object
```{r}
dag_object <- dagitty(dag_code)
```

turn the dag into a tibble
```{r}
tidy_dag_tibble <- tidy_dagitty(dag_object)

tidy_dag_tibble
```

next we want to extract the pairs of relationships which we have to plot for
```{r}
tidy_dag_tibble |> 
  as.data.frame() |>
  select(name, to) -> causal_relationship_combinations

saveRDS(causal_relationship_combinations, here("Output", "causal_relationship_combinations.RDS"))
```