---
title: "Figures to be presented"
format: pptx
---

Libraries
```{r}
#| echo: false
#| warning: false
library(here)
library(tidyverse)
library(lubridate)
library(knitr)
library(reshape2)
library(binom)
library(ggcorrplot)
library(patchwork)
library(car)
library(cowplot)

# custom functions
source(here("Scripts", "functions", "exploratory functions.R"))
```

Data
```{r}
# transformed independent variable data
ivd <-
  readRDS(
    here(
      "Data",
      "JACSIS2023", 
      "processed", 
      "transformed_independent_variable_data.RDS"
      )
    )

# transformed covid data
cov <-
  readRDS(
    here(
      "Data",
      "JACSIS2023", 
      "processed", 
      "transformed_covid_data.RDS"
    )
  )

# transformed influenza data
inf <-
  readRDS(
    here(
      "Data",
      "JACSIS2023", 
      "processed", 
      "transformed_influenza_data.RDS"
    )
  )

# transformed age data
age <- 
  readRDS(
    here(
      "Data",
      "JACSIS2023", 
      "processed", 
      "transformed_age_data.RDS"
    )
  )

# Creating data frames for bivariate and multivariate analysis
# limit indep data to only those households with a COI
prepped_ivd <- ivd |>
  mutate(age_of_interest = age$age_of_interest) |>
  filter(child_of_interest == 1)

# influenza and independent variable data
inf_prepped_ivd <- bind_cols(inf, ivd) |>
  mutate(age_of_interest = age$age_of_interest) |>
  filter(child_of_interest == 1 & !is.na(influenza_coverage_age)) 

# covid and independent variable data
cov_prepped_ivd <- bind_cols(cov, ivd) |>
  mutate(age_of_interest = age$age_of_interest) |>
  filter(child_of_interest == 1 & !is.na(covid_coverage_age))

# create dummy variables for both influenza and covid uptake response variables
inf_prepped_ivd |>
  model.matrix(~ influenza_coverage_age + 0, data = _) |>
  as.data.frame() -> inf_ivd_dummy_vars

cov_prepped_ivd |>
  model.matrix(~ covid_coverage_age + 0, data = _) |>
  as.data.frame() -> cov_ivd_dummy_vars


# create sets of data with dummy response variables for multinomial regresion fitting
# influenza
dummy_inf_prepped_ivd <-
  cbind(inf_ivd_dummy_vars, inf_prepped_ivd) |>
  select(-influenza_coverage_age)

# covid
dummy_cov_prepped_ivd <-
  cbind(cov_ivd_dummy_vars, cov_prepped_ivd) |>
  select(-covid_coverage_age)

```


## age_of_interest and age_cat vs siblings/birth order 
```{r}
# covid_uptake siblings
cov_prepped_ivd |>
  
  filter(!is.na(covid_coverage_age)) |>
  
  # filter out partial uptake
  filter(covid_coverage_age != 1) |>
  
  # rename sibling categories and compress them
  mutate(
     child_siblings = case_when(
      child_siblings == 0 ~ "No Siblings",
      child_siblings == 1 ~ "1 Sibling",
      child_siblings >= 2 ~ "2+ Siblings"
      ) |>
       factor(
         levels= c("No Siblings", "1 Sibling", "2+ Siblings")
       ),
    
    # segment age into increments of 0.5 years
    age_of_interest = round(age_of_interest * 2) / 2
  ) |>
  
  summarise(count = n(), .by = c(age_of_interest, covid_coverage_age, child_siblings, age_cat)) |>
  mutate(proportion = count / sum (count), .by = c(age_of_interest, child_siblings, age_cat)) |>
  arrange(child_siblings, age_of_interest, covid_coverage_age) |>
  
  mutate(
    # weight observations within each age_category, such that the trend for the proportion that have received each coverage is reflective of the sample size
    weights = count / sum(count), .by = c(age_cat, child_siblings, covid_coverage_age)
    
  ) |>
  
  # remove outliers where proportion = 1
  filter(proportion != 1) |>
  
  # rename coverage, number of siblings and schooling statuses
  mutate(
    covid_coverage_age = case_when(
      covid_coverage_age == 0 ~ "Unvaccinated",
      covid_coverage_age == 2 ~ "Fully Vaccinated"
    ),
    
    age_cat = case_when(
      age_cat == "pre" ~ "Preschool",
      age_cat == "primary" ~ "Primary school",
      age_cat == "high" ~ "(Junior) Highschool"
    )
  ) |>
   
  # plot graphs of covid coverage by age across different birth orders
  ggplot(aes(x = age_of_interest, y = proportion, colour = covid_coverage_age)) +
  geom_point(aes(shape = age_cat)) +
  geom_smooth(aes(linetype = age_cat, weight = weights), size = 0.75, alpha = 0.1, method = "lm") +
  facet_wrap(vars(child_siblings), ncol = 3) +
  labs(
    title = "Covid vaccination status with children's age,\n number of siblings and current level of schooling",
    x = "Age",
    y = "Proportion of children",
    col = "Covid vaccination status",
    shape = "Schooling category",
    linetype = "Schooling category"
  ) +
  
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.box = "vertical", # If you have multiple legends, arrange them vertically
    #legend.box.just = "top", # Align to the top of the legend box area
    #legend.justification = "top", # Justify the legend key within its area
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90")
  ) +
  
  guides(
    color = guide_legend(override.aes = list(fill = NA)),
    shape = guide_legend(override.aes = list(fill = NA)), 
    linetype = guide_legend(override.aes = list(fill = NA)) 
  )


# influenza
inf_prepped_ivd |>
  
  filter(!is.na(influenza_coverage_age)) |>
  
  # filter out partial uptake
  filter(influenza_coverage_age != 1) |>
  
  # rename sibling categories and compress them
  mutate(
     child_siblings = case_when(
      child_siblings == 0 ~ "No Siblings",
      child_siblings == 1 ~ "1 Sibling",
      child_siblings >= 2 ~ "2+ Siblings"
      ) |>
       factor(
         levels = c("No Siblings", "1 Sibling", "2+ Siblings")
       ),
    
    # segment age into increments of 0.5 years
    age_of_interest = round(age_of_interest * 2) / 2
  ) |>
  
  summarise(count = n(), .by = c(age_of_interest, influenza_coverage_age, child_siblings, age_cat)) |>
  mutate(proportion = count / sum (count), .by = c(age_of_interest, child_siblings, age_cat)) |>
  arrange(child_siblings, age_of_interest, influenza_coverage_age) |>
  
  mutate(
    # weight observations within each age_category, such that the trend for the proportion that have received each coverage is reflective of the sample size
    weights = count / sum(count), .by = c(age_cat, child_siblings, influenza_coverage_age)
    
  ) |>
  
  # remove outliers where proportion = 1
  filter(proportion != 1) |>
  
  # rename coverage, number of siblings and schooling statuses
  mutate(
    influenza_coverage_age = case_when(
      influenza_coverage_age == 0 ~ "Unvaccinated",
      influenza_coverage_age == 2 ~ "Fully Vaccinated"
    ),
    
    age_cat = case_when(
      age_cat == "pre" ~ "Preschool",
      age_cat == "primary" ~ "Primary school",
      age_cat == "high" ~ "(Junior) Highschool"
    )
  ) |>
   
  # plot graphs of covid coverage by age across different birth orders
  ggplot(aes(x = age_of_interest, y = proportion, colour = influenza_coverage_age)) +
  geom_point(aes(shape = age_cat)) +
  geom_smooth(aes(linetype = age_cat, weight = weights), size = 0.75, alpha = 0.1, method = "lm") +
  facet_wrap(vars(child_siblings), ncol = 3) +
  labs(
    title = "Influenza vaccination status with children's age,\nnumber of siblings and current level of schooling",
    x = "Age",
    y = "Proportion of children",
    col = "Influenza vaccination status",
    shape = "Schooling category",
    linetype = "Schooling category"
  ) +
  
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.box = "vertical", # If you have multiple legends, arrange them vertically
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90"),
  ) +
  
  # remove the backgrounds of the legend labels mapped to each aesthetic
  guides(
    color = guide_legend(override.aes = list(fill = NA)),
    shape = guide_legend(override.aes = list(fill = NA)), 
    linetype = guide_legend(override.aes = list(fill = NA)) 
  )
```

## parents_highest_education, test_household_income
```{r}
# covid coverage by age
cov_prepped_ivd |>
  filter(!is.na(parents_highest_education) & !is.na(covid_coverage_age) & !is.na(test_household_income)) |>
    
  
  # stratify income levels to compress them
  # mutate(test_household_income = ceiling(test_household_income / 4)) |>
  
  # stratify counts by income levels and education
  summarise(count = n(), .by = c(test_household_income, parents_highest_education, covid_coverage_age)) |>
  mutate(proportion = count / sum(count), .by = c(parents_highest_education, test_household_income)) |>
  
  # filter out outliers, partial coverage
  filter(proportion != 1, covid_coverage_age != 1) |>
   
  # rename coverage statuses
  mutate(
    covid_coverage_age = case_when(
      covid_coverage_age == 0 ~ "Unvaccinated",
      covid_coverage_age == 2 ~ "Fully Vaccinated"
    )
  ) |>
  
  # plot
  ggplot(aes(x = test_household_income, y = proportion, colour = covid_coverage_age)) +
  geom_point() +
  geom_smooth(aes(group = covid_coverage_age, weight = count), size = 0.75, alpha = 0.2, method = "lm") +
  labs(
    title = "Children's Covid vaccination status, stratified by\ntheir parents' highest educational attainment and household income",
    x = "Annual household income (millions of JPY)",
    y = "Proportion of children",
    col = "Covid vaccination status"
  ) +

  ylim(NA, 1) +
  
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90")
  ) +
  
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  
  facet_wrap(vars(parents_highest_education))
    
# influenza coverage by age
inf_prepped_ivd |>
  filter(!is.na(parents_highest_education) & !is.na(influenza_coverage_age) & !is.na(test_household_income)) |>
  
  # stratify income levels to compress them
  # mutate(income = ceiling(test_household_income / 4)) |>
  
  # stratify counts by income levels and education
  summarise(count = n(), .by = c(parents_highest_education, test_household_income, influenza_coverage_age)) |>
  mutate(proportion = count / sum(count), .by = c(parents_highest_education, test_household_income)) |>

  # filter out outliers, partial coverage
  filter(proportion != 1, influenza_coverage_age != 1) |>
  
  # rename coverage statuses
  mutate(
    influenza_coverage_age = case_when(
      influenza_coverage_age == 0 ~ "Unvaccinated",
      influenza_coverage_age == 2 ~ "Fully Vaccinated"
    )
  ) |>
  
  # plot
  ggplot(aes(x = test_household_income, y = proportion, colour = influenza_coverage_age)) +
  geom_point(alpha = 0.75) +
  geom_smooth(aes(group = influenza_coverage_age, weight = count), size = 0.75, alpha = 0.2, method = "lm") +
  labs(
    title = "Children's Influenza vaccination status, stratified by their\nparents' highest educational attainment and household income",
    x = "Annual household income (millions of JPY)",
    y = "Proportion of children",
    col = "Influenza vaccination status"
  ) +

  ylim(NA, 1) +
  
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90")
  ) +
  
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  
  facet_wrap(vars(parents_highest_education))

```

## perception of danger of infection
```{r}
# covid coverage
cov_prepped_ivd |>
     
   # stratify by vaccine danger and doses received
   filter(household_total > 1 & !is.na(covid_coverage_age)) |>
   group_by(perception_infection_danger, covid_coverage_age) |>

   # filter out partial uptake
   filter(covid_coverage_age != 1) |>
    
    # rename coverage statuses
    mutate(
      covid_coverage_age = case_when(
        covid_coverage_age == 0 ~ "Unvaccinated",
        covid_coverage_age == 2 ~ "Fully Vaccinated"
      ) |>
      factor(
        levels = c("Unvaccinated", "Fully Vaccinated")
      )
    ) |>
  
   # count the number of children in each category
   summarise(count = n()) |>
   ggplot() + 
   geom_col(
       aes(x = perception_infection_danger, y = count, fill = covid_coverage_age), 
       position = "fill"
   ) + 
  
  labs(
      title = "Children's Covid vaccination status,\nbased on their parents' perceived danger of infection",
      y = "Proportion of children",
      x = "Infection is dangerous, so I get my children vaccinated (strongly disagree to strongly agree)",
      fill = "Covid vaccination status"
    ) +
  
   theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90")
  ) +
  
  guides(color = guide_legend(override.aes = list(fill = NA)))


# influenza coverage
inf_prepped_ivd |>
     # stratify by vaccine danger and doses received
     filter(household_total > 1 & !is.na(influenza_coverage_age)) |>
     group_by(perception_infection_danger, influenza_coverage_age) |>
  
    # filter out partial uptake
    filter(influenza_coverage_age != 1) |>
  
    # rename coverage statuses
    mutate(
      influenza_coverage_age = case_when(
        influenza_coverage_age == 0 ~ "Unvaccinated",
        influenza_coverage_age == 2 ~ "Fully Vaccinated"
      ) |>
        factor(
          levels = c("Unvaccinated", "Fully Vaccinated")
        )
    ) |>
     
     # count the number of children in each category
     summarise(count = n()) |>
     ggplot() + 
     geom_col(
         aes(x = perception_infection_danger, y = count, fill = influenza_coverage_age), 
         position = "fill"
     ) + 
  
    labs(
      title = "Children's Influenza vaccination status,\nbased on their parents' perceived danger of infection",
      y = "Proportion of children",
      x = "Infection is dangerous, so I get my children vaccinated (strongly disagree to strongly agree)",
      fill = "Influenza vaccination status"
    ) +
  
  theme(
    text = element_text(family = "sans"),
    plot.title = element_text(size = 16, face = "bold", margin = margin(l = 15, b = 10)),
    plot.title.position = "plot",
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(lineheight = 0.5),
    legend.margin = margin(t = -10, r = 0, b = 0, l = 0),
    panel.grid.major = element_line(colour = "grey95"),
    panel.grid.minor = element_line(colour = "grey95"),
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(fill = "NA",colour = "grey90")
  ) +
  
  guides(color = guide_legend(override.aes = list(fill = NA)))

```